### PR TITLE
Applied Erwan Grelier's patch to allow for tensors of dimension>32

### PR DESCRIPTION
**Pull request by regislebrun**

### CODE REVIEW

**Comment by jschueller** [comment]
Looks like I'll be out of job soon ^^

**Comment by regislebrun** [comment]
Don't worry, you still have to fix the multidimensional output case ;-)!

**Comment by jschueller** [comment]
oh, that was not on my todo list

**Comment by regislebrun** [comment]
New version: don't worry, there are still bugs to fix in the multidimensional output case, if you are looking for additional work :-)

**Pull request merged**
